name: Docker Compose Actions Workflow
on: push
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      run: cd frontend && npm run test:lint
  test-backend:
    runs-on: ubuntu-latest
    steps:
      run: cd backend && npm run test:lint
    